### ISSUE TITLE
Reconnecting loxone / nodered cause automatic payload message

### ISSUE THREAD

**Issue by gisbern007** [codmpm/node-red-contrib-loxone#59]
Loxone firmware 11.1.9.14
Nodered 1.2.2
Loxone contrib 11.1.9.14

Do have two loxone "control in" (buttons in lox config) which controlling two zigbee2mqtt components "out" for danalock (lock / unlock)

When restarting loxone miniserver, or restart Nodered (restart flows), both loxone "control in's* generate payloads (firstly for "unlock", one sec after "lock". It means each lost/renew comunication between loxone and nodered automatically activate all loxone "control in" - in my case, restart open door :)

log after restart:
![dan](https://user-images.githubusercontent.com/75760298/101783311-6410f500-3afa-11eb-8be4-af0ebf672db5.jpg)
![dan2](https://user-images.githubusercontent.com/75760298/101783481-a0445580-3afa-11eb-9604-91f4ca892088.jpg)

Thank you

**Comment by codmpm** [comment]
Hey @gisbern007,

that's by design as the Loxone websocket sends the state of every attached control on (re-)connect. You can test this by comparing full-deploy and deploying only changed nodes.

The connect fires every event... that's the idea of event based flow driven programming ;-)
Same as connecting to an mqtt broker and getting every retained topic you've subscribed to.

Solve this using node-red's rbe-node, which only passes data if the payload has changed. 

Cheers,
Patrik

**Comment by gisbern007** [comment]
Hi, thank you for reply !! 
Understand it. To say a truth , realy dont know how to set rbe item, i tried change 0 , 1 various combinations but rbe didnt passthrough aby payloads ;-) but i used **switch node** 0- null -1 - go to lock. 

You really helped me understand restart behaviors.  Thank again for great programming work
Cheers G.
